services:
  backend:
    build: .
    working_dir: /application/project
    env_file:
      - src/.env
    # command: "tail -f /dev/null"
    entrypoint: ["src/entrypoint.sh"]
    volumes:
      - ../:/application/
      - ./staticfiles:/application/staticfiles
      - backend-python-site-packages:/usr/local/lib/python3.10/site-packages
      - backend-usr-local-bin:/usr/local/bin
      - ~/.ssh:/root/.ssh
    ports:
      - "8000:8000"

  db:
    image: postgres:15
    restart: always
    env_file:
      - src/.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  backend-python-site-packages:
    driver: local
  backend-usr-local-bin:
    driver: local
  pgdata:
    driver: local
